account/urls.py
from django.urls import path
from . import views
app_name = "account"
urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("signup/",views.SignUpView.as_view(), name="signup"),
    path("logout/",views.LogoutView.as_view(),name='logout'),

]

eventmanager/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    # path("admin/", admin.site.urls),
    path("",include("account.urls")),
    path("",include("events.urls")),

]

events/urls.py
from django.urls import path
from . import views
app_name = "events"
urlpatterns = [
    path("admin/", views.EvenView.as_view(), name="events"),
    path("admin/event/create/", views.EventCreateView.as_view(), name="createevent"),
    path("admin/<int:event_id>/event", views.EventDetailsView.as_view(), name="event_detail"),
    path("admin/<int:event_id>/delete/", views.EventDeleteView.as_view(), name="delete_event"),
    path("admin/profile/", views.AdminProfileView.as_view(), name="admin_profile"),
    path("admin/chat/", views.ChatBotView.as_view(), name="chatbot"),
    path('admin/generate/',views.GenerateResponseView.as_view(), name='generate_response'),
    path("seller/", views.SellerDashboard.as_view(), name="sellers"),
    path("seller/profile", views.SellerProfileView.as_view(), name="seller_profile"),
    path("seller/allevents", views.SellerAllEvenView.as_view(), name="seller_allevents"),
    path("seller/allevents/bottomtabl", views.EnrollmentView.as_view(), name="seller_allevents_bottomtab"),
    path("buyer/", views.BuyerDashboard.as_view(), name="buyers"),
 
]

templates/seller/allevent.html
{% extends "seller/base.html" %} {% block content %}
<div class="min-h-screen bg-gray-50 p-6">
  <div class="max-w-7xl mx-auto bg-white rounded-md md:p-8 sm:p-8 shadow-sm">
    <div class="relative flex items-center justify-center mb-6">
      <a
        href="{% url 'events:sellers' %}"
        class="absolute left-0 text-gray-600 hover:text-gray-900"
      >
        Back to seller
      </a>
      <h1 class="text-2xl font-medium text-center text-black">All events</h1>
    </div>

    <h1 class="text-2xl text-center text-black">
      Here is a list of all events
    </h1>
    <div class="max-w-7xl mx-auto bg-white rounded-[2rem] p-8 shadow-sm">
      <div
        class="grid grid-cols-1 text-start md:grid-cols-1 lg:grid-cols-3 gap-6 mb-8 mt-5 overflow-y-auto scrollbar-hide"
      >
        {% for event in events %}
        <div
          class="bg-white rounded-2xl shadow-[0_2px_8px_rgba(0,0,0,0.1)] p-6"
        >
          <h2 class="text-xl text-start font-medium text-gray-900 mb-2">
            {{ event.name }}
          </h2>
          <p class="text-gray-500 text-start mb-4">{{ event.event_time }}</p>
          <div class="flex justify-end">
            <a
              href="{% url 'events:event_detail' event.id %}"
              class="w-[150px] bg-[#2A2A2A] text-white py-3 rounded-lg hover:bg-black transition-colors text-center"
            >
              Manage Event
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% include "seller/allevents/bottomtab.html" %} {% endblock %}

templates/seller/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org@2.0.3"></script>
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.3/dist/cdn.min.js"
    ></script>
    <link
      href="https://cdn.jsdelivr.net/npm/daisyui@4.12.14/dist/full.min.css"
      rel="stylesheet"
      type="text/css"
    />

    <title>Event Manager</title>
  </head>
  <body class="bg-white">
    <main>{%block content%} {%endblock%}</main>
  </body>
</html>

templates/seller/bottomtab.html
<div class="p-8 max-w-2xl mx-auto">
  <div class="space-y-3">
    <button
      class="w-full text-black px-4 py-3 text-lg border-2 border-gray-200 rounded-md hover:bg-gray-50 transition-colors"
    >
      My Schedule
    </button>
    <button
      type="button"
      onclick="location.href='{% url 'events:seller_allevents' %}'"
      class="w-full px-4 py-3 text-lg bg-gray-900 text-white rounded-md hover:bg-gray-800 transition-colors"
    >
      All Events
    </button>
    <button
      type="button"
      onclick="location.href='{% url 'events:seller_profile' %}'"
      class="w-full px-4 py-3 text-lg bg-gray-900 text-white rounded-md hover:bg-gray-800 transition-colors"
    >
      Update Info
    </button>
    <div class="justify-center item-center text-center">
      <form method="post" action="{% url 'account:logout' %}" class="inline">
        {% csrf_token %}
        <button type="submit" class="text-lg text-black font-medium">
          Logout
        </button>
      </form>
    </div>
  </div>
</div>

templates/seller/index.html
{% extends "seller/base.html" %} {% block content %}
<h1>Seller Dashboard</h1>
{% include "seller/bottomtab.html" %} {% endblock %}

templates/seller/profile.html
{% extends "admin/base.html" %} {% block content %}
<div class="h-full w-full bg-white text-center">
  <div class="max-w-7xl mx-auto bg-white rounded-[2rem] p-8 shadow-sm">
    <div class="relative flex items-center justify-center mb-6">
      <a
        href="{% url 'events:events' %}"
        class="absolute left-0 text-gray-600 hover:text-gray-900"
        >Back to admin</a
      >
      <h1 class="text-2xl text-black font-medium text-center">
        Admin Account Information
      </h1>
    </div>

    <form class="mt-8 space-y-6 max-w-3xl mx-auto">
      <div class="space-y-4">
        <div>
          <label
            for="name"
            class="block text-sm font-medium text-gray-700 text-start"
            >Name</label
          >
          <input
            type="text"
            id="name"
            name="name"
            class="block text-black bg-white w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-gray-200 focus:border-gray-200"
            placeholder="Full name"
            value="{{ request.user.name}}"
          />
        </div>

        <div>
          <label
            for="email"
            class="block text-sm font-medium text-gray-700 text-start"
            >Email</label
          >
          <input
            type="email"
            id="email"
            name="email"
            class="block text-black bg-white w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-gray-200 focus:border-gray-200"
            placeholder="example@email.com"
            value="{{ request.user.email}}"
          />
        </div>

        <div>
          <label
            for="phone"
            class="block text-sm font-medium text-gray-700 text-start"
            >Phone</label
          >
          <input
            type="tel"
            id="phone"
            name="phone"
            class="block text-black bg-white w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-gray-200 focus:border-gray-200"
            placeholder="+44 012345"
            value="{{ request.user.phone}}"
          />
        </div>

        <div>
          <label
            for="company"
            class="block text-sm font-medium text-gray-700 text-start"
            >Company</label
          >
          <input
            type="text"
            id="company"
            name="company"
            class="block text-black bg-white w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-gray-200 focus:border-gray-200"
            placeholder="Company name"
            value="{{ request.user.company}}"
          />
        </div>

        <div>
          <label
            for="services"
            class="block text-sm font-medium text-gray-700 text-start"
            >Products/Services</label
          >
          <textarea
            id="services"
            name="services"
            rows="4"
            class="block text-black bg-white w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-gray-200 focus:border-gray-200"
            placeholder="Description"
          >
        {{request.user.services}}</textarea
          >
        </div>

        <div>
          <label
            for="password"
            class="block text-sm font-medium text-gray-700 text-start"
            >New Password</label
          >
          <div class="relative">
            <input
              type="password"
              id="password"
              name="password"
              class="block text-black bg-white w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-gray-200 focus:border-gray-200"
              placeholder="Enter password"
            />
            <button
              type="button"
              class="absolute inset-y-0 right-3 text-sm text-gray-600 focus:outline-none"
              onclick="togglePasswordVisibility()"
            >
              Show
            </button>
          </div>
        </div>
      </div>

      <div class="space-y-3">
        <button
          type="submit"
          class="w-full px-4 py-3 text-lg bg-gray-900 text-white rounded-md hover:bg-gray-800 transition-colors"
        >
          Update
        </button>
        <button
          onclick="location.href='{% url 'events:events' %}'"
          type="button"
          class="w-full text-black px-4 py-3 text-lg border-2 border-gray-200 rounded-md hover:bg-gray-50 transition-colors"
        >
          Cancel
        </button>
      </div>
    </form>
  </div>
</div>

<script>
  function togglePasswordVisibility() {
    const passwordInput = document.getElementById("password");
    const isPasswordVisible = passwordInput.type === "password";
    passwordInput.type = isPasswordVisible ? "text" : "password";
  }
</script>
{% endblock %}