account/urls.py
from django.urls import path
from . import views
app_name = "account"
urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("signup/",views.SignUpView.as_view(), name="signup"),
    path("logout/",views.LogoutView.as_view(),name='logout'),

]

eventmanager/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    # path("admin/", admin.site.urls),
    path("",include("account.urls")),
    path("",include("events.urls")),

]

events/urls.py
from django.urls import path
from . import views
app_name = "events"
urlpatterns = [
    path("admin/", views.EvenView.as_view(), name="events"),
    path("admin/event/create/", views.EventCreateView.as_view(), name="createevent"),
    path("admin/<int:event_id>/event", views.EventDetailsView.as_view(), name="event_detail"),
    path("admin/<int:event_id>/delete/", views.EventDeleteView.as_view(), name="delete_event"),
    path("admin/profile/", views.AdminProfileView.as_view(), name="admin_profile"),
    path("admin/chat/", views.ChatBotView.as_view(), name="chatbot"),
    path('admin/generate/',views.GenerateResponseView.as_view(), name='generate_response'),
    path("seller/", views.SellerDashboard.as_view(), name="sellers"),
    path("seller/profile", views.SellerProfileView.as_view(), name="seller_profile"),
    path("seller/allevents", views.SellerAllEvenView.as_view(), name="seller_allevents"),
    path("seller/allevents/bottomtabl", views.EnrollmentView.as_view(), name="seller_allevents_bottomtab"),
    path("buyer/", views.BuyerDashboard.as_view(), name="buyers"),
 
]

templates/buyer/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/htmx.org@2.0.3"></script>
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.3/dist/cdn.min.js"
    ></script>
    <link
      href="https://cdn.jsdelivr.net/npm/daisyui@4.12.14/dist/full.min.css"
      rel="stylesheet"
      type="text/css"
    />

    <title>Event Manager</title>
  </head>
  <body class="bg-white">
    <main>{%block content%} {%endblock%}</main>
  </body>
</html>

templates/buyer/bottomtab.html
<div class="p-8 max-w-2xl mx-auto">
  <div class="space-y-3">
    <button
      class="w-full text-black px-4 py-3 text-lg border-2 border-gray-200 rounded-md hover:bg-gray-50 transition-colors"
    >
      View All Attendees
    </button>
    <button
      type="button"
      onclick="location.href='{% url 'events:createevent' %}'"
      class="w-full px-4 py-3 text-lg bg-gray-900 text-white rounded-md hover:bg-gray-800 transition-colors"
    >
      Create Events
    </button>
    <button
      type="button"
      onclick="location.href='{% url 'events:admin_profile' %}'"
      class="w-full px-4 py-3 text-lg bg-gray-900 text-white rounded-md hover:bg-gray-800 transition-colors"
    >
      Update Info
    </button>
    <div class="justify-center item-center text-center">
      <form method="post" action="{% url 'account:logout' %}" class="inline">
        {% csrf_token %}
        <button type="submit" class="text-lg text-black font-medium">
          Logout
        </button>
      </form>
    </div>
  </div>
</div>

templates/buyer/index.html
{% extends "buyer/base.html" %} {% block content %}
<h1>Buyer Dabhaord</h1>
{% include "buyer/bottomtab.html" %} {% endblock %}