account/urls.py
from django.urls import path
from . import views
app_name = "account"
urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("signup/",views.SignUpView.as_view(), name="signup"),
    path("logout/",views.LogoutView.as_view(),name='logout'),

]

eventmanager/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    # path("admin/", admin.site.urls),
    path("",include("account.urls")),
    path("",include("events.urls")),

]

events/urls.py
from django.urls import path
from . import views
app_name = "events"
urlpatterns = [
    path("admin/", views.EvenView.as_view(), name="events"),
    path("admin/event/create/", views.EventCreateView.as_view(), name="createevent"),
    path("admin/<int:event_id>/event", views.EventDetailsView.as_view(), name="event_detail"),
    path("admin/<int:event_id>/delete/", views.EventDeleteView.as_view(), name="delete_event"),
    path("admin/profile/", views.AdminProfileView.as_view(), name="admin_profile"),
    path("admin/chat/", views.ChatBotView.as_view(), name="chatbot"),
    path('admin/generate/',views.GenerateResponseView.as_view(), name='generate_response'),
    path("seller/", views.SellerDashboard.as_view(), name="sellers"),
    path("seller/profile", views.SellerProfileView.as_view(), name="seller_profile"),
    path("seller/allevents", views.SellerAllEvenView.as_view(), name="seller_allevents"),
    path("seller/allevents/bottomtabl", views.EnrollmentView.as_view(), name="seller_allevents_bottomtab"),
    path("buyer/", views.BuyerDashboard.as_view(), name="buyers"),
 
]

templates/seller/allevents/bottomtab.html
<div class="p-8 max-w-2xl mx-auto">
  <div class="space-y-3">
    <!-- You can open the modal using ID.showModal() method -->
    <button
      class="w-full px-4 py-3 text-lg bg-gray-900 text-white rounded-md hover:bg-gray-800 transition-colors"
      onclick="my_modal_3.showModal()"
    >
      Enter event invite code
    </button>
    <dialog id="my_modal_3" class="modal">
      <div class="modal-box relative bg-gray-100">
        <form method="dialog">
          <button
            class="btn btn-sm text-black btn-circle btn-ghost absolute right-4 top-4"
            style="z-index: 10"
          >
            ✕
          </button>
        </form>
        <form
          method="post"
          action="{% url 'events:seller_allevents_bottomtab' %}"
        >
          {% csrf_token %}
          <div class="mt-6 mb-4">
            <input
              type="text"
              id="invite_code "
              name="invite_code"
              class="block bg-white text-black w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-gray-200 focus:border-gray-200"
              placeholder="Enter invite code"
              required
            />
          </div>

          <div class="flex justify-end space-x-2">
            <button
              type="button"
              class="px-8 py-2 bg-red-500 text-white rounded-lg hover:bg-red-400 transition-colors"
              onclick="my_modal_3.close()"
            >
              Cancel
            </button>
            <button
              type="submit"
              class="px-8 py-2 bg-[#2A2A2A] text-white rounded-lg hover:bg-black transition-colors"
            >
              Confirm
            </button>
          </div>
        </form>
      </div>
    </dialog>
    <div class="justify-center item-center text-center">
      <form method="post" action="{% url 'account:logout' %}" class="inline">
        {% csrf_token %}
        <button type="submit" class="text-lg font-medium text-black">
          Logout
        </button>
      </form>
    </div>
  </div>
</div>